# Generated by Django 4.0.5 on 2023-02-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('furigana', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
    ]
