# Generated by Django 4.0.5 on 2023-02-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0003_alter_curriculums_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculums',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
