# Generated by Django 4.0.5 on 2023-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0004_alter_curriculums_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculums',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='current_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='current_address_furigana',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='period_of_stay',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='postal_cde',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='status_of_residence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curriculums',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='curriculums',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='curriculums',
            name='furigana',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
