# Generated by Django 4.0.5 on 2023-02-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0005_curriculums_age_curriculums_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curriculums',
            new_name='User',
        ),
    ]
