# Generated by Django 4.0.5 on 2023-02-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0006_rename_curriculums_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacgroundSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('education', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenceOrQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('license_or_qualification', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('furigana', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('postal_cde', models.IntegerField(null=True)),
                ('current_address', models.CharField(max_length=100, null=True)),
                ('current_address_furigana', models.CharField(max_length=100, null=True)),
                ('status_of_residence', models.CharField(max_length=100, null=True)),
                ('period_of_stay', models.DateTimeField(null=True)),
                ('japanese_level', models.CharField(choices=[('N5', 'N5'), ('N5 勉強中', 'N5 勉強中'), ('N4', 'N4'), ('N4 勉強中', 'N4 勉強中'), ('N3', 'N3'), ('N3 勉強中', 'N3 勉強中'), ('N2', 'N2'), ('N2 勉強中', 'N2 勉強中'), ('N1', 'N1'), ('N1 勉強中', 'N1 勉強中')], max_length=20, null=True)),
                ('english_level', models.CharField(choices=[('Business', 'Business'), ('Fluent', 'Fluent'), ('Conversational', 'Conversational')], max_length=20, null=True)),
                ('hobbie', models.CharField(max_length=20)),
                ('Reason_for_coming', models.CharField(max_length=1000, null=True)),
                ('motifation', models.CharField(max_length=1000, null=True)),
                ('request', models.CharField(max_length=500, null=True)),
                ('dependens', models.IntegerField(null=True)),
                ('pairs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('spouse_support_obligation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('work', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
