# Generated by Django 4.0.5 on 2023-02-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0007_bacgroundschool_licenceorqualification_personaldata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacgroundschool',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bacgroundschool',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bacgroundschool',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bacgroundschool',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenceorqualification',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='licenceorqualification',
            name='license_or_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='licenceorqualification',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenceorqualification',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='Reason_for_coming',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='current_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='current_address_furigana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='dependens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='english_level',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Fluent', 'Fluent'), ('Conversational', 'Conversational')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='furigana',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='japanese_level',
            field=models.CharField(blank=True, choices=[('N5', 'N5'), ('N5 勉強中', 'N5 勉強中'), ('N4', 'N4'), ('N4 勉強中', 'N4 勉強中'), ('N3', 'N3'), ('N3 勉強中', 'N3 勉強中'), ('N2', 'N2'), ('N2 勉強中', 'N2 勉強中'), ('N1', 'N1'), ('N1 勉強中', 'N1 勉強中')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='motifation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='pairs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='period_of_stay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='postal_cde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='request',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='spouse_support_obligation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='status_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
