# Generated by Django 4.0.5 on 2023-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0008_alter_bacgroundschool_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='period_of_stay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
