# Generated by Django 4.0.5 on 2023-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0009_alter_personaldata_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='Reason_for_coming',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='motifation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='request',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
