# Generated by Django 4.0.5 on 2023-02-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0010_alter_personaldata_reason_for_coming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='default_language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
