# Generated by Django 4.0.5 on 2023-02-04 08:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0011_personaldata_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='media/images/%Y/%m/%d/'),
        ),
    ]
