# Generated by Django 4.0.5 on 2023-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0013_graduationbacgroundschool_leavingworkhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacgroundSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_country', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('admission_month', models.IntegerField(blank=True, null=True)),
                ('admission_education', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_country', models.CharField(blank=True, max_length=20, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('graduation_month', models.IntegerField(blank=True, null=True)),
                ('graduation_education', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Join_country', models.CharField(blank=True, max_length=20, null=True)),
                ('Join_year', models.IntegerField(blank=True, null=True)),
                ('Join_month', models.IntegerField(blank=True, null=True)),
                ('Join_work', models.CharField(blank=True, max_length=100, null=True)),
                ('Leave_country', models.CharField(blank=True, max_length=20, null=True)),
                ('Leave_year', models.IntegerField(blank=True, null=True)),
                ('Leave_month', models.IntegerField(blank=True, null=True)),
                ('Leave_work', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdmissionBacgroundSchool',
        ),
        migrations.DeleteModel(
            name='GraduationBacgroundSchool',
        ),
        migrations.DeleteModel(
            name='JoiningWorkHistory',
        ),
        migrations.DeleteModel(
            name='LeavingWorkHistory',
        ),
    ]
