# Generated by Django 4.0.5 on 2023-02-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0014_bacgroundschool_workhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bacgroundschool',
            old_name='admission_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='bacgroundschool',
            old_name='admission_education',
            new_name='education',
        ),
        migrations.RemoveField(
            model_name='bacgroundschool',
            name='graduation_country',
        ),
        migrations.RemoveField(
            model_name='bacgroundschool',
            name='graduation_education',
        ),
    ]
