# Generated by Django 4.0.5 on 2023-02-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0015_rename_admission_country_bacgroundschool_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistory',
            old_name='Join_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='Join_month',
            new_name='join_month',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='Join_year',
            new_name='join_year',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='Leave_month',
            new_name='leave_month',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='Leave_year',
            new_name='leave_year',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='Join_work',
            new_name='work',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='Leave_country',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='Leave_work',
        ),
    ]
