# Generated by Django 4.0.5 on 2023-02-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0016_rename_join_country_workhistory_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacgroundschool',
            name='part_time',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
    ]
