# Generated by Django 4.0.5 on 2023-02-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0017_bacgroundschool_part_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacgroundschool',
            name='part_time',
        ),
        migrations.AddField(
            model_name='workhistory',
            name='part_time',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
    ]
