# Generated by Django 4.0.5 on 2023-02-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0018_remove_bacgroundschool_part_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='pairs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='spouse_support_obligation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='part_time',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, null=True),
        ),
    ]
