# Generated by Django 4.0.5 on 2023-02-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0019_alter_personaldata_pairs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='postal_cde',
            new_name='postal_code',
        ),
    ]
