# Generated by Django 4.0.5 on 2023-02-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0020_rename_postal_cde_personaldata_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='status_of_residence',
            field=models.CharField(blank=True, default='技術・人文知識・国際業務', max_length=100, null=True),
        ),
    ]
