# Generated by Django 4.0.5 on 2023-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0023_alter_personaldata_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='photo_tes',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
    ]
