# Generated by Django 4.0.5 on 2023-02-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0026_skill_alter_personaldata_hobbie'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_level', models.CharField(blank=True, choices=[('N5', 'N5'), ('N5 勉強中', 'N5 勉強中'), ('N4', 'N4'), ('N4 勉強中', 'N4 勉強中'), ('N3', 'N3'), ('N3 勉強中', 'N3 勉強中'), ('N2', 'N2'), ('N2 勉強中', 'N2 勉強中'), ('N1', 'N1'), ('N1 勉強中', 'N1 勉強中')], max_length=20, null=True)),
                ('english_level', models.CharField(blank=True, choices=[('Business', 'Business'), ('Fluent', 'Fluent'), ('Conversational', 'Conversational')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='english_level',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='japanese_level',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='photo_tes',
        ),
    ]
