# Generated by Django 4.0.5 on 2023-02-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0033_alter_bacgroundschool_personal_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='author',
            new_name='personal_user',
        ),
    ]
