# Generated by Django 4.0.5 on 2023-02-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CurriculumVitae', '0034_rename_author_personaldata_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageskill',
            name='personal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='championed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
