# Generated by Django 4.0.5 on 2023-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0038_alter_personaldata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', '男'), ('Female', '女')], max_length=6, null=True),
        ),
    ]
